### ISSUE TITLE
EdgeGPT版本问题

### ISSUE THREAD

**Issue by nice2cu1** [jzitan/NewBing_QQ_bot#1]
能否提供运行环境的EdgeGPT版本，requirements中并没有定义版本号，在运行run.sh后，对机器人输入文件会得到`Chatbot.__init__() got an unexpected keyword argument 'cookiePath'`的异常，也许是EdgeGPT更新后修改了参数名？

我将cookiePath直接更改为cookie后仍然报错`string indices must be integers`

![image](https://github.com/jzitan/NewBing_QQ_bot/assets/33564254/069637b7-a54e-41d2-8163-2db0c9ce2c0d)

**Comment by jzitan** [comment]
我这里EdgeGPT的版本是0.1.23，但我觉得应该不是这个的问题，如果cookies.json在py文件夹下的话config.json中像这样填写就好
![image](https://github.com/jzitan/NewBing_QQ_bot/assets/111671261/629d3ccc-1a1a-454d-a2cb-ad2962f4412c)
如果不在这个目录下请使用绝对路径，顺便检查一下文件名是否写错

**Comment by ha-h-ha** [comment]
> 能否提供运行环境的EdgeGPT版本，requirements中并没有定义版本号，在运行 run.sh 后，对机器人输入文件会得到的异常，也许是EdgeGPT更新后修改了参数名？`Chatbot.__init__() got an unexpected keyword argument 'cookiePath'`
> 
> 我将cookiePath直接更改为cookie后仍然报错`string indices must be integers`
> 
> ![图像](https://user-images.githubusercontent.com/33564254/240468757-069637b7-a54e-41d2-8163-2db0c9ce2c0d.png)

我这里EdgeGPT的版本是0.1.23，但我觉得应该不是这个的问题，如果cookies.json在py文件夹下的话config.json中像这样填写就好
![image](https://github.com/jzitan/NewBing_QQ_bot/assets/111671261/629d3ccc-1a1a-454d-a2cb-ad2962f4412c)
如果不在这个目录下请使用绝对路径，顺便检查一下文件名是否写错

**Comment by nice2cu1** [comment]
> > 能否提供运行环境的EdgeGPT版本，requirements中并没有定义版本号，在运行 run.sh 后，对机器人输入文件会得到的异常，也许是EdgeGPT更新后修改了参数名？`Chatbot.__init__() got an unexpected keyword argument 'cookiePath'`
> > 我将cookiePath直接更改为cookie后仍然报错`string indices must be integers`
> > ![图像](https://user-images.githubusercontent.com/33564254/240468757-069637b7-a54e-41d2-8163-2db0c9ce2c0d.png)
> 
> 我这里EdgeGPT的版本是0.1.23，但我觉得应该不是这个的问题，如果cookies.json在py文件夹下的话config.json中像这样填写就好 ![image](https://user-images.githubusercontent.com/111671261/240473736-629d3ccc-1a1a-454d-a2cb-ad2962f4412c.png) 如果不在这个目录下请使用绝对路径，顺便检查一下文件名是否写错

非常感谢，将EdgeGPT版本进行降级以后成功运行
